### ISSUE TITLE
Reach out

### ISSUE THREAD

**Issue by shunlinlu** [fyyakaxyy/animationGPT#1]
Hi, 

Your project is very interesting. Is there any chance to communicate with you? My email address is shunlinlu0803@gmail.com. 

Shunlin

**Comment by fyyakaxyy** [comment]
> Hi,
> 
> Your project is very interesting. Is there any chance to communicate with you? My email address is [shunlinlu0803@gmail.com](mailto:shunlinlu0803@gmail.com).
> 
> Shunlin

Okay！ I will contact you by email.
