### ISSUE TITLE
生产动作接入引擎的后处理

### ISSUE THREAD

**Issue by Dragon2938734** [fyyakaxyy/AnimationGPT#11]
Hello, I am a student from the University of Science and Technology of China (USTC) and am very interested in this project. However, when I attempted to replicate it, I found that the BVH files produced by A-GPT caused character jitter and abnormal foot-to-ground contact after being imported into the engine (but the animations on your website appear to be more stable). I would like to ask if you have made any operations related to the integration with the engine? Thank you!

**Comment by Gelercatty** [comment]
i also wants to know，i retargeted the bvh to fbx, and then use it in unity, it shows rotation error and poor quaility, can you provide more details about the operation in demo?

**Comment by fyyakaxyy** [comment]
> i also wants to know，i retargeted the bvh to fbx, and then use it in unity, it shows rotation error and poor quaility, can you provide more details about the operation in demo?

maybe useful
link: https://pan.baidu.com/s/1ED9HfueuB6x_QLVfv-KjeQ?pwd=qxph
key: qxph

**Comment by fyyakaxyy** [comment]
> i also wants to know，i retargeted the bvh to fbx, and then use it in unity, it shows rotation error and poor quaility, can you provide more details about the operation in demo?

Please leave your contact information, such as email
