### ISSUE TITLE
About Kit ML

### ISSUE THREAD

**Issue by Pride-Huang** [fyyakaxyy/AnimationGPT#18]
Hello, this is a good work. Is the semantic of the joints helpful for the performance? I want to know which joints have been used in KIT ML dataset, and what their names are. Have you utilized it in AnimationGPT?

**Comment by fyyakaxyy** [comment]
> Hello, this is a good work. Is the semantic of the joints helpful for the performance? I want to know which joints have been used in KIT ML dataset, and what their names are. Have you utilized it in AnimationGPT?

1. "Is the semantic of the joints helpful for the performance?", I haven't tried.
2. We process the dataset in HumanML3D format, not KIT-ML format.
