### ISSUE TITLE
Could you provide the keys_mapping file?

### ISSUE THREAD

**Issue by hushaoqing** [fyyakaxyy/animationGPT#2]
dataset/Motion-X/motionx2amass.ipynb

![image](https://github.com/fyyakaxyy/animationGPT/assets/10289162/b86341aa-a983-4afc-9d70-4b6a44d489ee)

**Comment by fyyakaxyy** [comment]
> dataset/Motion-X/motionx2amass.ipynb
> 
> ![image](https://private-user-images.githubusercontent.com/10289162/309975111-b86341aa-a983-4afc-9d70-4b6a44d489ee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MTcyNDEsIm5iZiI6MTcwOTYxNjk0MSwicGF0aCI6Ii8xMDI4OTE2Mi8zMDk5NzUxMTEtYjg2MzQxYWEtYTk4My00YWZjLTlkNzAtNGI2YTQ0ZDQ4OWVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDA1MzU0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3NzdlMDMwMDBjN2U4OTEzZjcxNDA3M2EzZDY5MWI1ZGVkNTQ3YTk1OGNkZDZmMGNhNGY4ZmVkZTNkYzZhODcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FhkNBW43rCLWi98r_zDOAVBFfI6J6PtoiiUaP7nQzl0)

[keys_mapping.csv](https://github.com/fyyakaxyy/animationGPT/files/14490887/keys_mapping.csv)

**Comment by hushaoqing** [comment]
thx

> > dataset/Motion-X/motionx2amass.ipynb
> > ![image](https://private-user-images.githubusercontent.com/10289162/309975111-b86341aa-a983-4afc-9d70-4b6a44d489ee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MTcyNDEsIm5iZiI6MTcwOTYxNjk0MSwicGF0aCI6Ii8xMDI4OTE2Mi8zMDk5NzUxMTEtYjg2MzQxYWEtYTk4My00YWZjLTlkNzAtNGI2YTQ0ZDQ4OWVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDA1MzU0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3NzdlMDMwMDBjN2U4OTEzZjcxNDA3M2EzZDY5MWI1ZGVkNTQ3YTk1OGNkZDZmMGNhNGY4ZmVkZTNkYzZhODcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FhkNBW43rCLWi98r_zDOAVBFfI6J6PtoiiUaP7nQzl0)
> 
> [keys_mapping.csv](https://github.com/fyyakaxyy/animationGPT/files/14490887/keys_mapping.csv)

thx
