### ISSUE TITLE
CMP data seems strange

### ISSUE THREAD

**Issue by tucker666** [fyyakaxyy/AnimationGPT#3]
thanks a million for your great work.
I download the CMP dataset, the feature seems strange, here is the 263 feature plot of CMP000001.npy

![image](https://github.com/fyyakaxyy/AnimationGPT/assets/53161743/ed3ef2ac-cca4-4068-9161-17f50b248245)

I also test the MDM model trained by CMP, but the result seems that a person is always steal just like the feature data.
looking forward for your reply

**Comment by fyyakaxyy** [comment]
> thanks a million for your great work. I download the CMP dataset, the feature seems strange, here is the 263 feature plot of CMP000001.npy
> 
> ![image](https://private-user-images.githubusercontent.com/53161743/323825282-ed3ef2ac-cca4-4068-9161-17f50b248245.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1MDEzODIsIm5iZiI6MTcxMzUwMTA4MiwicGF0aCI6Ii81MzE2MTc0My8zMjM4MjUyODItZWQzZWYyYWMtY2NhNC00MDY4LTkxNjEtMTdmNTBiMjQ4MjQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDA0MzEyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyNTQ4ZGNmMDNkMTRhNjI4MjU4MGJhOTA2Zjk0NTk4MmJjNjU3ZjM5NDM2NWNiYmZiNTIyNzQ3ZWNlMzdiZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.d0kyKmG5kUNbN86xQa0w6R4jwFDzgUUu-cUmwlB35Pg)
> 
> I also test the MDM model trained by CMP, but the result seems that a person is always steal just like the feature data. looking forward for your reply

Thank you for your interest in CMP!
In fact, the MDM generation results we trained on the CMP dataset were not very good, which may be due to our dataset being too stylized.
Also, I don't understand the feature maps. The dimensional features are in accordance with the format of the HumanML3D dataset. For example, the following code shows the dimensional information of one of the data in the HumanML3D dataset:
![image](https://github.com/fyyakaxyy/AnimationGPT/assets/70080768/78549bd6-435f-4670-846f-af9859efcbe8)

Can you draw a feature map of this file: https://github.com/EricGuo5513/HumanML3D/blob/main/HumanML3D/new_joint_vecs/012314.npy

**Comment by tucker666** [comment]
> > thanks a million for your great work. I download the CMP dataset, the feature seems strange, here is the 263 feature plot of CMP000001.npy
> > ![image](https://private-user-images.githubusercontent.com/53161743/323825282-ed3ef2ac-cca4-4068-9161-17f50b248245.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1MDEzODIsIm5iZiI6MTcxMzUwMTA4MiwicGF0aCI6Ii81MzE2MTc0My8zMjM4MjUyODItZWQzZWYyYWMtY2NhNC00MDY4LTkxNjEtMTdmNTBiMjQ4MjQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDA0MzEyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyNTQ4ZGNmMDNkMTRhNjI4MjU4MGJhOTA2Zjk0NTk4MmJjNjU3ZjM5NDM2NWNiYmZiNTIyNzQ3ZWNlMzdiZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.d0kyKmG5kUNbN86xQa0w6R4jwFDzgUUu-cUmwlB35Pg)
> > I also test the MDM model trained by CMP, but the result seems that a person is always steal just like the feature data. looking forward for your reply
> 
> Thank you for your interest in CMP! In fact, the MDM generation results we trained on the CMP dataset were not very good, which may be due to our dataset being too stylized. Also, I don't understand the feature maps. The dimensional features are in accordance with the format of the HumanML3D dataset. For example, the following code shows the dimensional information of one of the data in the HumanML3D dataset: ![image](https://private-user-images.githubusercontent.com/70080768/323832659-78549bd6-435f-4670-846f-af9859efcbe8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1MDczNTAsIm5iZiI6MTcxMzUwNzA1MCwicGF0aCI6Ii83MDA4MDc2OC8zMjM4MzI2NTktNzg1NDliZDYtNDM1Zi00NjcwLTg0NmYtYWY5ODU5ZWZjYmU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDA2MTA1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzYTY2ZmU2YTJhNTZlYzBjYmY2YjU4ZTEzZjNlMmNkYmU1OTk3NmMzMDNlN2IxZDAzOWE0ZmZhZmFhN2YwNDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dEtENfssMgghMswYM31FN7Umh3whrSUdmG_Pl_RF-Mo)
> 
> Can you draw a feature map of this file: https://github.com/EricGuo5513/HumanML3D/blob/main/HumanML3D/new_joint_vecs/012314.npy

hi ,i just plot 263 features by the timeline, so there is 263 lines in the plot. the format is correct, but the movement seems very small. 
the left is the visualization of 012314.npy while the right is that of CMP000001.npy
![output_c](https://github.com/fyyakaxyy/AnimationGPT/assets/53161743/c0c19c7c-09d0-4d9c-9bb8-59e3e4332c8b)

![output_012314](https://github.com/fyyakaxyy/AnimationGPT/assets/53161743/8540f71e-5dc8-4c11-9c85-6e066a71c6c2)

maybe the animation of  CMP000001.npy is still ? 
i think too many still movements in CMP may lead to the result of MDM training.
here are some training results on CMP by MDM

https://github.com/fyyakaxyy/AnimationGPT/assets/53161743/36a13219-961a-48d4-9dec-b78688f8aafc

**Comment by fyyakaxyy** [comment]
> > > thanks a million for your great work. I download the CMP dataset, the feature seems strange, here is the 263 feature plot of CMP000001.npy
> > > ![image](https://private-user-images.githubusercontent.com/53161743/323825282-ed3ef2ac-cca4-4068-9161-17f50b248245.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1MDEzODIsIm5iZiI6MTcxMzUwMTA4MiwicGF0aCI6Ii81MzE2MTc0My8zMjM4MjUyODItZWQzZWYyYWMtY2NhNC00MDY4LTkxNjEtMTdmNTBiMjQ4MjQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDA0MzEyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyNTQ4ZGNmMDNkMTRhNjI4MjU4MGJhOTA2Zjk0NTk4MmJjNjU3ZjM5NDM2NWNiYmZiNTIyNzQ3ZWNlMzdiZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.d0kyKmG5kUNbN86xQa0w6R4jwFDzgUUu-cUmwlB35Pg)
> > > I also test the MDM model trained by CMP, but the result seems that a person is always steal just like the feature data. looking forward for your reply
> > 
> > 
> > Thank you for your interest in CMP! In fact, the MDM generation results we trained on the CMP dataset were not very good, which may be due to our dataset being too stylized. Also, I don't understand the feature maps. The dimensional features are in accordance with the format of the HumanML3D dataset. For example, the following code shows the dimensional information of one of the data in the HumanML3D dataset: ![image](https://private-user-images.githubusercontent.com/70080768/323832659-78549bd6-435f-4670-846f-af9859efcbe8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1MDczNTAsIm5iZiI6MTcxMzUwNzA1MCwicGF0aCI6Ii83MDA4MDc2OC8zMjM4MzI2NTktNzg1NDliZDYtNDM1Zi00NjcwLTg0NmYtYWY5ODU5ZWZjYmU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDA2MTA1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzYTY2ZmU2YTJhNTZlYzBjYmY2YjU4ZTEzZjNlMmNkYmU1OTk3NmMzMDNlN2IxZDAzOWE0ZmZhZmFhN2YwNDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dEtENfssMgghMswYM31FN7Umh3whrSUdmG_Pl_RF-Mo)
> > Can you draw a feature map of this file: https://github.com/EricGuo5513/HumanML3D/blob/main/HumanML3D/new_joint_vecs/012314.npy
> 
> hi ,i just plot 263 features by the timeline, so there is 263 lines in the plot. the format is correct, but the movement seems very small. the left is the visualization of 012314.npy while the right is that of CMP000001.npy ![output_c](https://private-user-images.githubusercontent.com/53161743/323850130-c0c19c7c-09d0-4d9c-9bb8-59e3e4332c8b.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1MTA5MjMsIm5iZiI6MTcxMzUxMDYyMywicGF0aCI6Ii81MzE2MTc0My8zMjM4NTAxMzAtYzBjMTljN2MtMDlkMC00ZDljLTliYjgtNTllM2U0MzMyYzhiLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDA3MTAyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3Y2ZlMDVjOTI1ZjA4ZjY4OGJmNDBkMjY4Njc0YjYxYmExMTZiNmJkZjgyYmVlZTdhNmZlY2Q3NTgwNmRjZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uxlmZOMKVmbzNNNKxEaFLohl5YMPvjpGHJoCv2lZILw) [ ![output_c](https://private-user-images.githubusercontent.com/53161743/323850130-c0c19c7c-09d0-4d9c-9bb8-59e3e4332c8b.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1MTA5MjMsIm5iZiI6MTcxMzUxMDYyMywicGF0aCI6Ii81MzE2MTc0My8zMjM4NTAxMzAtYzBjMTljN2MtMDlkMC00ZDljLTliYjgtNTllM2U0MzMyYzhiLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDA3MTAyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3Y2ZlMDVjOTI1ZjA4ZjY4OGJmNDBkMjY4Njc0YjYxYmExMTZiNmJkZjgyYmVlZTdhNmZlY2Q3NTgwNmRjZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uxlmZOMKVmbzNNNKxEaFLohl5YMPvjpGHJoCv2lZILw) ](https://private-user-images.githubusercontent.com/53161743/323850130-c0c19c7c-09d0-4d9c-9bb8-59e3e4332c8b.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1MTA5MjMsIm5iZiI6MTcxMzUxMDYyMywicGF0aCI6Ii81MzE2MTc0My8zMjM4NTAxMzAtYzBjMTljN2MtMDlkMC00ZDljLTliYjgtNTllM2U0MzMyYzhiLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDA3MTAyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3Y2ZlMDVjOTI1ZjA4ZjY4OGJmNDBkMjY4Njc0YjYxYmExMTZiNmJkZjgyYmVlZTdhNmZlY2Q3NTgwNmRjZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uxlmZOMKVmbzNNNKxEaFLohl5YMPvjpGHJoCv2lZILw) [ ](https://private-user-images.githubusercontent.com/53161743/323850130-c0c19c7c-09d0-4d9c-9bb8-59e3e4332c8b.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1MTA5MjMsIm5iZiI6MTcxMzUxMDYyMywicGF0aCI6Ii81MzE2MTc0My8zMjM4NTAxMzAtYzBjMTljN2MtMDlkMC00ZDljLTliYjgtNTllM2U0MzMyYzhiLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDA3MTAyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3Y2ZlMDVjOTI1ZjA4ZjY4OGJmNDBkMjY4Njc0YjYxYmExMTZiNmJkZjgyYmVlZTdhNmZlY2Q3NTgwNmRjZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uxlmZOMKVmbzNNNKxEaFLohl5YMPvjpGHJoCv2lZILw)
> 
> ![output_012314](https://private-user-images.githubusercontent.com/53161743/323850095-8540f71e-5dc8-4c11-9c85-6e066a71c6c2.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1MTA5MjMsIm5iZiI6MTcxMzUxMDYyMywicGF0aCI6Ii81MzE2MTc0My8zMjM4NTAwOTUtODU0MGY3MWUtNWRjOC00YzExLTljODUtNmUwNjZhNzFjNmMyLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDA3MTAyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3ZjAzZDg3ZTA1ZjA1NTUwM2Q2M2M3MDk2MzIzOTI1NzM2MDc1ZTk0OWU2ZjU5YTE4ZTA0ZTMzYzc0NGU0NDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9wSHpB_4pihudlW5bnHoEyLudoOfBElkkzEC-__Q5Ys) [ ![output_012314](https://private-user-images.githubusercontent.com/53161743/323850095-8540f71e-5dc8-4c11-9c85-6e066a71c6c2.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1MTA5MjMsIm5iZiI6MTcxMzUxMDYyMywicGF0aCI6Ii81MzE2MTc0My8zMjM4NTAwOTUtODU0MGY3MWUtNWRjOC00YzExLTljODUtNmUwNjZhNzFjNmMyLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDA3MTAyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3ZjAzZDg3ZTA1ZjA1NTUwM2Q2M2M3MDk2MzIzOTI1NzM2MDc1ZTk0OWU2ZjU5YTE4ZTA0ZTMzYzc0NGU0NDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9wSHpB_4pihudlW5bnHoEyLudoOfBElkkzEC-__Q5Ys) ](https://private-user-images.githubusercontent.com/53161743/323850095-8540f71e-5dc8-4c11-9c85-6e066a71c6c2.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1MTA5MjMsIm5iZiI6MTcxMzUxMDYyMywicGF0aCI6Ii81MzE2MTc0My8zMjM4NTAwOTUtODU0MGY3MWUtNWRjOC00YzExLTljODUtNmUwNjZhNzFjNmMyLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDA3MTAyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3ZjAzZDg3ZTA1ZjA1NTUwM2Q2M2M3MDk2MzIzOTI1NzM2MDc1ZTk0OWU2ZjU5YTE4ZTA0ZTMzYzc0NGU0NDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9wSHpB_4pihudlW5bnHoEyLudoOfBElkkzEC-__Q5Ys) [ ](https://private-user-images.githubusercontent.com/53161743/323850095-8540f71e-5dc8-4c11-9c85-6e066a71c6c2.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1MTA5MjMsIm5iZiI6MTcxMzUxMDYyMywicGF0aCI6Ii81MzE2MTc0My8zMjM4NTAwOTUtODU0MGY3MWUtNWRjOC00YzExLTljODUtNmUwNjZhNzFjNmMyLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDA3MTAyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3ZjAzZDg3ZTA1ZjA1NTUwM2Q2M2M3MDk2MzIzOTI1NzM2MDc1ZTk0OWU2ZjU5YTE4ZTA0ZTMzYzc0NGU0NDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9wSHpB_4pihudlW5bnHoEyLudoOfBElkkzEC-__Q5Ys)
> 
> maybe the animation of CMP000001.npy is still ? i think too many still movements in CMP may lead to the result of MDM training. here are some training results on CMP by MDM
> 
>  combat.mp4

Thanks for your results, The text of CMP000001.npy is "a man Idle ,root motion get In-Place,Steady and Uniform Speed."
I guess the model focuses on understanding the word "Idle".
We will consider your suggestions in the subsequent optimization of the dataset.
