### ISSUE TITLE
matplotlib version issue in animation.py

### ISSUE THREAD

**Issue by kcfmwls** [fyyakaxyy/AnimationGPT#4]
遇到一个小问题~
animation.py文件里注释着使用matplotlib==3.3.3
https://github.com/fyyakaxyy/AnimationGPT/blob/cca051a9e535fe9ec226bc62d81543d4ed320605/tools/animation.py#L3
但是python3.10并不支持这个版本，使用默认的3.8.4或是最低的3.5.1会有三处报错
ax.lines = []和ax.collections = []不能直接赋值为空，以及ani.save无法识别.mp4文件

我的系统是window10，python==3.10.6，matplotlib==3.8.4
（有可能是操作系统问题？但我没验证过ubuntu上是什么情况……而且似乎3.3.3在任何系统最高只支持到python3.9了）

谢谢·-·

**Comment by fyyakaxyy** [comment]
> 遇到一个小问题~ animation.py文件里注释着使用matplotlib==3.3.3
> 
> https://github.com/fyyakaxyy/AnimationGPT/blob/cca051a9e535fe9ec226bc62d81543d4ed320605/tools/animation.py#L3
> 
> 
> 但是python3.10并不支持这个版本，使用默认的3.8.4或是最低的3.5.1会有三处报错
> ax.lines = []和ax.collections = []不能直接赋值为空，以及ani.save无法识别.mp4文件
> 我的系统是window10，python==3.10.6，matplotlib==3.8.4 （有可能是操作系统问题？但我没验证过ubuntu上是什么情况……而且似乎3.3.3在任何系统最高只支持到python3.9了）
> 
> 谢谢·-·

您好，我没有在win10测试过。
此前在服务器跑代码时我也遇到过这个问题，这个报错是matplotlib版本引起的，参考：https://github.com/GuyTevet/motion-diffusion-model/issues/6
如果win10中当前环境无法安装3.3.3版本的matplotlib，可以尝试额外创建一个环境用于渲染视频

**Comment by kcfmwls** [comment]
> > 遇到一个小问题~ animation.py文件里注释着使用matplotlib==3.3.3
> > https://github.com/fyyakaxyy/AnimationGPT/blob/cca051a9e535fe9ec226bc62d81543d4ed320605/tools/animation.py#L3
> > 
> > 但是python3.10并不支持这个版本，使用默认的3.8.4或是最低的3.5.1会有三处报错
> > ax.lines = []和ax.collections = []不能直接赋值为空，以及ani.save无法识别.mp4文件
> > 我的系统是window10，python==3.10.6，matplotlib==3.8.4 （有可能是操作系统问题？但我没验证过ubuntu上是什么情况……而且似乎3.3.3在任何系统最高只支持到python3.9了）
> > 谢谢·-·
> 
> 您好，我没有在win10测试过。 此前在服务器跑代码时我也遇到过这个问题，这个报错是matplotlib版本引起的，参考：[GuyTevet/motion-diffusion-model#6](https://github.com/GuyTevet/motion-diffusion-model/issues/6) 如果win10中当前环境无法安装3.3.3版本的matplotlib，可以尝试额外创建一个环境用于渲染视频

谢谢作者大大，解决了
我另起了一个py3.9.19环境去做npy转换anim和bvh，视频和动捕都正常转换了
中间改了一部分因为numpy和matplotlib版本造成的报错，我看看后面有空的话提个pr上来（

**Comment by fyyakaxyy** [comment]
> > > 遇到一个小问题~ animation.py文件里注释着使用matplotlib==3.3.3
> > > https://github.com/fyyakaxyy/AnimationGPT/blob/cca051a9e535fe9ec226bc62d81543d4ed320605/tools/animation.py#L3
> > > 
> > > 但是python3.10并不支持这个版本，使用默认的3.8.4或是最低的3.5.1会有三处报错
> > > ax.lines = []和ax.collections = []不能直接赋值为空，以及ani.save无法识别.mp4文件
> > > 我的系统是window10，python==3.10.6，matplotlib==3.8.4 （有可能是操作系统问题？但我没验证过ubuntu上是什么情况……而且似乎3.3.3在任何系统最高只支持到python3.9了）
> > > 谢谢·-·
> > 
> > 
> > 您好，我没有在win10测试过。 此前在服务器跑代码时我也遇到过这个问题，这个报错是matplotlib版本引起的，参考：[GuyTevet/motion-diffusion-model#6](https://github.com/GuyTevet/motion-diffusion-model/issues/6) 如果win10中当前环境无法安装3.3.3版本的matplotlib，可以尝试额外创建一个环境用于渲染视频
> 
> 谢谢作者大大，解决了 我另起了一个py3.9.19环境去做npy转换anim和bvh，视频和动捕都正常转换了 中间改了一部分因为numpy和matplotlib版本造成的报错，我看看后面有空的话提个pr上来（

不好意思，我刚才准备在win10上测试你的修改，拉取项目时发现文件很大。在清理冗余文件的时候覆盖了之前的提交记录，导致你提的pr被关了，有空的话能否在清理后的项目基础上重新提一次？
