### ISSUE TITLE
About training on CMP

### ISSUE THREAD

**Issue by Kelvar00** [fyyakaxyy/AnimationGPT#6]
so what we need to do is to alter the humanml3d folder in MotionGPT  and train stage1-3 as the MotionGPT repo instructs?

or just stage2-3/ stage 3

**Comment by fyyakaxyy** [comment]
> so what we need to do is to alter the humanml3d folder in MotionGPT and train stage1-3 as the MotionGPT repo instructs?
> 
> or just stage2-3/ stage 3

yes, "alter the humanml3d folder in MotionGPT and train stage1-3 as the MotionGPT repo instructs"
