### ISSUE TITLE
评价指标

### ISSUE THREAD

**Issue by GuangtaoLyu** [fyyakaxyy/AnimationGPT#8]
我今天用作者的权重试了一下评价指标，在我的环境下测出来和作者提供的差不多。
但是我突然想起来一个问题，作者测试时，评价指标所用的权重有没有重新训练过。有些指标在计算时用了一些预训练权重。这些权重作者有没有在重新训练。

**Comment by GuangtaoLyu** [comment]
> 我今天用作者的权重试了一下评价指标，在我的环境下测出来和作者提供的差不多。 但是我突然想起来一个问题，作者测试时，评价指标所用的权重有没有重新训练过。有些指标在计算时用了一些预训练权重。这些权重作者有没有在重新训练。

理论上是不是应该用在combat上预训练的编码器来测试。

**Comment by fyyakaxyy** [comment]
好问题，我此前没注意到，近期看一下

**Comment by fyyakaxyy** [comment]
不好意思回复晚了，我最近用T2M的评估器在CMP数据集上训练了[evaluator](https://drive.google.com/file/d/1iL_PNRcgNzO5iiAgeypkeE9eJt67IpJa/view?usp=sharing)，已经更新了评估指标。感谢您的建议！
