### ISSUE TITLE
Example of prompt

### ISSUE THREAD

**Issue by Dragon2938734** [fyyakaxyy/AnimationGPT#9]
"Save the prompt in input.txt", is there any examples of prompt for this step? thanks!

**Comment by fyyakaxyy** [comment]
> "Save the prompt in input.txt", is there any examples of prompt for this step? thanks!

just write prompts in a txt file:
![image](https://github.com/fyyakaxyy/AnimationGPT/assets/70080768/87c0d134-f3b5-4842-a6cf-4f86e5e4f178)
